(() => {
    const data = 'forward 4\n' +
        'down 8\n' +
        'down 1\n' +
        'forward 6\n' +
        'forward 7\n' +
        'down 7\n' +
        'forward 3\n' +
        'forward 5\n' +
        'up 9\n' +
        'down 1\n' +
        'forward 5\n' +
        'down 8\n' +
        'forward 4\n' +
        'forward 5\n' +
        'down 5\n' +
        'down 1\n' +
        'forward 1\n' +
        'down 3\n' +
        'forward 5\n' +
        'forward 5\n' +
        'down 1\n' +
        'up 2\n' +
        'down 2\n' +
        'down 5\n' +
        'down 5\n' +
        'forward 3\n' +
        'forward 7\n' +
        'forward 5\n' +
        'forward 9\n' +
        'forward 8\n' +
        'down 4\n' +
        'down 6\n' +
        'up 5\n' +
        'down 1\n' +
        'forward 6\n' +
        'up 3\n' +
        'forward 7\n' +
        'forward 4\n' +
        'down 7\n' +
        'up 5\n' +
        'up 5\n' +
        'up 1\n' +
        'up 5\n' +
        'forward 5\n' +
        'forward 2\n' +
        'forward 7\n' +
        'down 7\n' +
        'forward 9\n' +
        'down 9\n' +
        'up 8\n' +
        'up 8\n' +
        'up 2\n' +
        'forward 5\n' +
        'forward 8\n' +
        'up 5\n' +
        'forward 1\n' +
        'down 1\n' +
        'down 6\n' +
        'forward 1\n' +
        'forward 2\n' +
        'forward 4\n' +
        'forward 6\n' +
        'up 4\n' +
        'up 5\n' +
        'down 4\n' +
        'down 9\n' +
        'down 4\n' +
        'forward 4\n' +
        'up 8\n' +
        'up 2\n' +
        'down 2\n' +
        'up 9\n' +
        'forward 9\n' +
        'forward 4\n' +
        'forward 1\n' +
        'forward 6\n' +
        'up 3\n' +
        'forward 6\n' +
        'forward 2\n' +
        'up 3\n' +
        'down 3\n' +
        'forward 6\n' +
        'down 9\n' +
        'down 7\n' +
        'forward 3\n' +
        'up 7\n' +
        'up 8\n' +
        'forward 3\n' +
        'down 1\n' +
        'down 8\n' +
        'forward 7\n' +
        'forward 3\n' +
        'down 2\n' +
        'down 5\n' +
        'forward 5\n' +
        'forward 1\n' +
        'down 1\n' +
        'down 3\n' +
        'down 5\n' +
        'forward 1\n' +
        'down 1\n' +
        'down 7\n' +
        'forward 1\n' +
        'up 2\n' +
        'down 5\n' +
        'up 3\n' +
        'up 2\n' +
        'down 7\n' +
        'up 4\n' +
        'forward 2\n' +
        'down 3\n' +
        'down 1\n' +
        'up 7\n' +
        'down 6\n' +
        'down 1\n' +
        'forward 7\n' +
        'down 5\n' +
        'down 2\n' +
        'forward 7\n' +
        'up 9\n' +
        'forward 6\n' +
        'forward 6\n' +
        'forward 2\n' +
        'forward 6\n' +
        'down 2\n' +
        'forward 4\n' +
        'down 5\n' +
        'forward 4\n' +
        'down 8\n' +
        'forward 3\n' +
        'down 9\n' +
        'up 5\n' +
        'forward 6\n' +
        'down 5\n' +
        'forward 5\n' +
        'down 4\n' +
        'down 1\n' +
        'forward 3\n' +
        'up 9\n' +
        'up 5\n' +
        'up 9\n' +
        'down 3\n' +
        'forward 7\n' +
        'forward 7\n' +
        'up 5\n' +
        'up 6\n' +
        'up 3\n' +
        'down 9\n' +
        'down 4\n' +
        'up 8\n' +
        'down 9\n' +
        'down 6\n' +
        'forward 5\n' +
        'down 6\n' +
        'forward 7\n' +
        'down 4\n' +
        'down 9\n' +
        'down 9\n' +
        'forward 6\n' +
        'down 4\n' +
        'up 2\n' +
        'down 8\n' +
        'up 3\n' +
        'up 7\n' +
        'up 1\n' +
        'forward 9\n' +
        'down 4\n' +
        'down 8\n' +
        'up 2\n' +
        'forward 7\n' +
        'forward 5\n' +
        'down 9\n' +
        'down 9\n' +
        'up 5\n' +
        'down 4\n' +
        'forward 8\n' +
        'up 3\n' +
        'up 4\n' +
        'up 8\n' +
        'down 7\n' +
        'forward 6\n' +
        'down 8\n' +
        'down 1\n' +
        'up 1\n' +
        'down 7\n' +
        'down 7\n' +
        'forward 3\n' +
        'down 9\n' +
        'up 2\n' +
        'forward 2\n' +
        'up 1\n' +
        'up 1\n' +
        'down 2\n' +
        'down 8\n' +
        'up 5\n' +
        'down 3\n' +
        'down 3\n' +
        'forward 2\n' +
        'down 4\n' +
        'forward 2\n' +
        'down 2\n' +
        'forward 3\n' +
        'down 6\n' +
        'forward 8\n' +
        'down 5\n' +
        'down 6\n' +
        'forward 9\n' +
        'forward 2\n' +
        'down 6\n' +
        'down 4\n' +
        'up 9\n' +
        'forward 2\n' +
        'forward 1\n' +
        'up 9\n' +
        'down 9\n' +
        'forward 8\n' +
        'down 4\n' +
        'up 3\n' +
        'down 1\n' +
        'forward 9\n' +
        'forward 9\n' +
        'forward 3\n' +
        'forward 4\n' +
        'down 2\n' +
        'down 1\n' +
        'forward 5\n' +
        'up 3\n' +
        'forward 6\n' +
        'down 8\n' +
        'down 8\n' +
        'down 7\n' +
        'forward 1\n' +
        'forward 6\n' +
        'down 9\n' +
        'down 6\n' +
        'forward 8\n' +
        'down 5\n' +
        'up 6\n' +
        'down 2\n' +
        'forward 2\n' +
        'up 3\n' +
        'forward 6\n' +
        'forward 4\n' +
        'up 4\n' +
        'down 5\n' +
        'forward 2\n' +
        'down 5\n' +
        'forward 1\n' +
        'forward 5\n' +
        'up 7\n' +
        'up 1\n' +
        'down 3\n' +
        'up 8\n' +
        'forward 4\n' +
        'forward 8\n' +
        'forward 8\n' +
        'up 2\n' +
        'down 8\n' +
        'up 2\n' +
        'up 2\n' +
        'up 7\n' +
        'down 9\n' +
        'down 1\n' +
        'forward 1\n' +
        'down 3\n' +
        'down 1\n' +
        'down 4\n' +
        'forward 3\n' +
        'down 4\n' +
        'down 5\n' +
        'forward 7\n' +
        'forward 6\n' +
        'forward 7\n' +
        'forward 8\n' +
        'up 6\n' +
        'down 1\n' +
        'down 9\n' +
        'up 2\n' +
        'up 2\n' +
        'forward 1\n' +
        'up 9\n' +
        'forward 6\n' +
        'down 2\n' +
        'forward 6\n' +
        'forward 8\n' +
        'up 8\n' +
        'down 6\n' +
        'forward 2\n' +
        'up 4\n' +
        'up 5\n' +
        'down 3\n' +
        'down 2\n' +
        'forward 7\n' +
        'down 8\n' +
        'forward 4\n' +
        'forward 8\n' +
        'up 4\n' +
        'down 7\n' +
        'forward 6\n' +
        'forward 1\n' +
        'up 4\n' +
        'down 4\n' +
        'down 9\n' +
        'down 7\n' +
        'down 6\n' +
        'down 1\n' +
        'forward 7\n' +
        'up 3\n' +
        'down 1\n' +
        'down 9\n' +
        'down 9\n' +
        'down 1\n' +
        'down 7\n' +
        'down 8\n' +
        'up 9\n' +
        'down 7\n' +
        'up 4\n' +
        'forward 4\n' +
        'down 2\n' +
        'up 8\n' +
        'down 6\n' +
        'down 6\n' +
        'forward 4\n' +
        'up 5\n' +
        'down 9\n' +
        'down 8\n' +
        'up 7\n' +
        'down 4\n' +
        'forward 9\n' +
        'up 3\n' +
        'down 6\n' +
        'forward 7\n' +
        'up 4\n' +
        'forward 9\n' +
        'down 6\n' +
        'forward 6\n' +
        'down 3\n' +
        'down 5\n' +
        'down 4\n' +
        'up 5\n' +
        'down 8\n' +
        'down 8\n' +
        'forward 5\n' +
        'forward 1\n' +
        'down 3\n' +
        'forward 7\n' +
        'down 3\n' +
        'up 6\n' +
        'forward 5\n' +
        'up 7\n' +
        'forward 8\n' +
        'down 1\n' +
        'forward 7\n' +
        'forward 8\n' +
        'forward 9\n' +
        'forward 7\n' +
        'up 5\n' +
        'forward 9\n' +
        'up 7\n' +
        'down 7\n' +
        'forward 8\n' +
        'down 8\n' +
        'up 6\n' +
        'down 4\n' +
        'forward 6\n' +
        'forward 3\n' +
        'forward 3\n' +
        'forward 6\n' +
        'down 3\n' +
        'up 4\n' +
        'down 3\n' +
        'down 8\n' +
        'forward 2\n' +
        'down 1\n' +
        'down 5\n' +
        'forward 2\n' +
        'up 3\n' +
        'up 5\n' +
        'forward 2\n' +
        'forward 8\n' +
        'down 7\n' +
        'down 9\n' +
        'forward 8\n' +
        'forward 5\n' +
        'forward 2\n' +
        'down 3\n' +
        'forward 6\n' +
        'forward 3\n' +
        'forward 4\n' +
        'forward 9\n' +
        'down 8\n' +
        'forward 2\n' +
        'down 6\n' +
        'down 8\n' +
        'forward 1\n' +
        'forward 5\n' +
        'up 3\n' +
        'forward 8\n' +
        'up 3\n' +
        'forward 2\n' +
        'down 3\n' +
        'down 5\n' +
        'up 4\n' +
        'down 9\n' +
        'up 5\n' +
        'down 2\n' +
        'forward 7\n' +
        'forward 8\n' +
        'forward 2\n' +
        'forward 4\n' +
        'forward 6\n' +
        'down 1\n' +
        'up 3\n' +
        'forward 3\n' +
        'up 6\n' +
        'forward 1\n' +
        'down 9\n' +
        'forward 4\n' +
        'forward 5\n' +
        'forward 3\n' +
        'down 7\n' +
        'down 9\n' +
        'forward 1\n' +
        'forward 5\n' +
        'up 1\n' +
        'down 6\n' +
        'down 7\n' +
        'up 4\n' +
        'up 7\n' +
        'forward 2\n' +
        'down 7\n' +
        'forward 5\n' +
        'up 9\n' +
        'up 8\n' +
        'forward 8\n' +
        'up 1\n' +
        'up 6\n' +
        'down 7\n' +
        'up 8\n' +
        'forward 2\n' +
        'down 1\n' +
        'forward 7\n' +
        'forward 6\n' +
        'forward 2\n' +
        'up 7\n' +
        'down 5\n' +
        'down 6\n' +
        'forward 8\n' +
        'down 3\n' +
        'down 2\n' +
        'forward 5\n' +
        'down 7\n' +
        'forward 2\n' +
        'down 9\n' +
        'forward 7\n' +
        'forward 9\n' +
        'forward 1\n' +
        'down 7\n' +
        'down 3\n' +
        'down 8\n' +
        'down 4\n' +
        'up 1\n' +
        'down 2\n' +
        'forward 5\n' +
        'forward 9\n' +
        'forward 5\n' +
        'up 6\n' +
        'up 1\n' +
        'forward 3\n' +
        'forward 1\n' +
        'forward 7\n' +
        'down 9\n' +
        'forward 4\n' +
        'down 7\n' +
        'up 6\n' +
        'forward 1\n' +
        'down 7\n' +
        'forward 5\n' +
        'down 4\n' +
        'down 2\n' +
        'up 1\n' +
        'forward 6\n' +
        'up 6\n' +
        'down 3\n' +
        'up 5\n' +
        'down 8\n' +
        'down 5\n' +
        'forward 2\n' +
        'down 1\n' +
        'forward 8\n' +
        'forward 4\n' +
        'down 3\n' +
        'forward 3\n' +
        'forward 6\n' +
        'forward 2\n' +
        'forward 9\n' +
        'forward 2\n' +
        'down 3\n' +
        'forward 8\n' +
        'down 4\n' +
        'down 1\n' +
        'forward 4\n' +
        'down 1\n' +
        'forward 5\n' +
        'down 5\n' +
        'down 6\n' +
        'forward 6\n' +
        'down 6\n' +
        'down 9\n' +
        'forward 7\n' +
        'down 6\n' +
        'forward 6\n' +
        'forward 7\n' +
        'forward 1\n' +
        'forward 4\n' +
        'forward 2\n' +
        'forward 3\n' +
        'up 8\n' +
        'down 3\n' +
        'down 7\n' +
        'forward 6\n' +
        'forward 4\n' +
        'up 7\n' +
        'forward 6\n' +
        'forward 6\n' +
        'down 7\n' +
        'up 8\n' +
        'down 5\n' +
        'forward 6\n' +
        'forward 8\n' +
        'down 3\n' +
        'up 2\n' +
        'down 5\n' +
        'forward 2\n' +
        'forward 5\n' +
        'up 8\n' +
        'forward 1\n' +
        'down 3\n' +
        'forward 3\n' +
        'forward 2\n' +
        'down 3\n' +
        'down 8\n' +
        'forward 3\n' +
        'forward 1\n' +
        'down 5\n' +
        'down 1\n' +
        'up 1\n' +
        'forward 9\n' +
        'down 7\n' +
        'up 2\n' +
        'forward 8\n' +
        'down 6\n' +
        'down 5\n' +
        'up 9\n' +
        'forward 2\n' +
        'forward 5\n' +
        'forward 8\n' +
        'up 2\n' +
        'up 5\n' +
        'forward 2\n' +
        'down 2\n' +
        'down 9\n' +
        'down 3\n' +
        'forward 7\n' +
        'up 5\n' +
        'forward 7\n' +
        'down 6\n' +
        'forward 2\n' +
        'forward 7\n' +
        'forward 8\n' +
        'forward 8\n' +
        'down 7\n' +
        'forward 3\n' +
        'forward 6\n' +
        'down 5\n' +
        'forward 8\n' +
        'forward 6\n' +
        'up 2\n' +
        'forward 1\n' +
        'up 9\n' +
        'forward 1\n' +
        'up 3\n' +
        'forward 6\n' +
        'down 4\n' +
        'down 5\n' +
        'down 8\n' +
        'up 6\n' +
        'forward 1\n' +
        'down 8\n' +
        'forward 3\n' +
        'forward 2\n' +
        'forward 9\n' +
        'down 5\n' +
        'down 9\n' +
        'forward 5\n' +
        'down 7\n' +
        'up 9\n' +
        'forward 5\n' +
        'forward 7\n' +
        'forward 6\n' +
        'forward 5\n' +
        'down 3\n' +
        'forward 6\n' +
        'down 9\n' +
        'up 8\n' +
        'forward 4\n' +
        'forward 7\n' +
        'forward 3\n' +
        'down 7\n' +
        'forward 8\n' +
        'down 5\n' +
        'forward 3\n' +
        'up 6\n' +
        'up 5\n' +
        'forward 9\n' +
        'up 4\n' +
        'up 9\n' +
        'forward 9\n' +
        'forward 3\n' +
        'down 8\n' +
        'forward 8\n' +
        'down 3\n' +
        'forward 2\n' +
        'down 4\n' +
        'down 1\n' +
        'forward 2\n' +
        'up 9\n' +
        'down 7\n' +
        'forward 4\n' +
        'up 3\n' +
        'down 9\n' +
        'down 6\n' +
        'forward 2\n' +
        'forward 5\n' +
        'down 7\n' +
        'down 2\n' +
        'forward 8\n' +
        'down 5\n' +
        'forward 8\n' +
        'down 8\n' +
        'down 4\n' +
        'down 1\n' +
        'down 2\n' +
        'forward 5\n' +
        'down 8\n' +
        'down 1\n' +
        'down 2\n' +
        'forward 8\n' +
        'forward 3\n' +
        'down 8\n' +
        'up 8\n' +
        'up 8\n' +
        'down 3\n' +
        'forward 3\n' +
        'forward 6\n' +
        'down 9\n' +
        'up 1\n' +
        'forward 6\n' +
        'up 1\n' +
        'down 1\n' +
        'down 9\n' +
        'forward 3\n' +
        'up 1\n' +
        'forward 7\n' +
        'forward 6\n' +
        'forward 1\n' +
        'up 3\n' +
        'down 8\n' +
        'forward 7\n' +
        'down 3\n' +
        'down 5\n' +
        'down 7\n' +
        'forward 6\n' +
        'down 9\n' +
        'forward 9\n' +
        'forward 8\n' +
        'down 9\n' +
        'forward 1\n' +
        'down 2\n' +
        'up 7\n' +
        'down 3\n' +
        'down 1\n' +
        'forward 8\n' +
        'forward 4\n' +
        'forward 9\n' +
        'up 9\n' +
        'down 4\n' +
        'forward 1\n' +
        'down 1\n' +
        'up 1\n' +
        'up 1\n' +
        'up 6\n' +
        'down 7\n' +
        'down 5\n' +
        'forward 1\n' +
        'forward 7\n' +
        'up 3\n' +
        'down 7\n' +
        'up 3\n' +
        'down 4\n' +
        'up 9\n' +
        'up 9\n' +
        'forward 1\n' +
        'down 4\n' +
        'down 6\n' +
        'forward 2\n' +
        'forward 6\n' +
        'up 1\n' +
        'forward 1\n' +
        'down 8\n' +
        'forward 7\n' +
        'up 6\n' +
        'forward 6\n' +
        'forward 3\n' +
        'up 1\n' +
        'up 6\n' +
        'forward 1\n' +
        'down 2\n' +
        'forward 8\n' +
        'forward 4\n' +
        'forward 2\n' +
        'down 3\n' +
        'forward 2\n' +
        'forward 3\n' +
        'forward 1\n' +
        'down 6\n' +
        'forward 7\n' +
        'forward 7\n' +
        'down 4\n' +
        'forward 6\n' +
        'up 3\n' +
        'up 4\n' +
        'up 6\n' +
        'down 7\n' +
        'down 8\n' +
        'forward 3\n' +
        'down 2\n' +
        'forward 5\n' +
        'down 4\n' +
        'forward 6\n' +
        'forward 7\n' +
        'forward 8\n' +
        'forward 9\n' +
        'forward 3\n' +
        'down 1\n' +
        'forward 8\n' +
        'forward 1\n' +
        'down 8\n' +
        'up 1\n' +
        'down 3\n' +
        'down 6\n' +
        'down 1\n' +
        'up 1\n' +
        'forward 1\n' +
        'down 6\n' +
        'down 5\n' +
        'forward 6\n' +
        'down 1\n' +
        'down 5\n' +
        'forward 7\n' +
        'up 3\n' +
        'forward 4\n' +
        'forward 4\n' +
        'forward 1\n' +
        'up 6\n' +
        'up 2\n' +
        'up 4\n' +
        'down 4\n' +
        'up 4\n' +
        'forward 8\n' +
        'up 8\n' +
        'forward 1\n' +
        'down 5\n' +
        'forward 5\n' +
        'down 7\n' +
        'up 5\n' +
        'up 7\n' +
        'up 5\n' +
        'forward 9\n' +
        'down 1\n' +
        'down 1\n' +
        'forward 4\n' +
        'down 2\n' +
        'down 2\n' +
        'down 3\n' +
        'down 1\n' +
        'forward 1\n' +
        'up 7\n' +
        'forward 6\n' +
        'forward 9\n' +
        'up 5\n' +
        'forward 1\n' +
        'forward 9\n' +
        'up 2\n' +
        'forward 5\n' +
        'down 4\n' +
        'forward 6\n' +
        'down 9\n' +
        'down 3\n' +
        'forward 1\n' +
        'down 2\n' +
        'down 3\n' +
        'down 1\n' +
        'down 3\n' +
        'forward 8\n' +
        'up 6\n' +
        'forward 2\n' +
        'down 5\n' +
        'down 9\n' +
        'down 4\n' +
        'up 2\n' +
        'up 9\n' +
        'forward 2\n' +
        'down 7\n' +
        'forward 9\n' +
        'down 5\n' +
        'down 5\n' +
        'up 6\n' +
        'forward 1\n' +
        'forward 5\n' +
        'forward 9\n' +
        'down 4\n' +
        'forward 2\n' +
        'forward 7\n' +
        'down 2\n' +
        'forward 4\n' +
        'down 2\n' +
        'forward 3\n' +
        'down 3\n' +
        'down 2\n' +
        'up 5\n' +
        'forward 8\n' +
        'up 8\n' +
        'down 9\n' +
        'forward 9\n' +
        'down 9\n' +
        'down 4\n' +
        'down 1\n' +
        'forward 4\n' +
        'forward 9\n' +
        'down 5\n' +
        'down 9\n' +
        'down 4\n' +
        'down 5\n' +
        'forward 1\n' +
        'down 3\n' +
        'down 3\n' +
        'down 4\n' +
        'forward 6\n' +
        'forward 5\n' +
        'down 3\n' +
        'up 4\n' +
        'forward 9\n' +
        'forward 5\n' +
        'forward 3\n' +
        'forward 6\n' +
        'down 8\n' +
        'up 9\n' +
        'forward 2\n' +
        'up 6\n' +
        'forward 2\n' +
        'down 9\n' +
        'up 9\n' +
        'down 4\n' +
        'forward 1\n' +
        'forward 9\n' +
        'down 5\n' +
        'forward 9\n' +
        'forward 4\n' +
        'down 6\n' +
        'forward 7\n' +
        'forward 4\n' +
        'down 7\n' +
        'down 1\n' +
        'forward 9\n' +
        'down 6\n' +
        'down 5\n' +
        'forward 5\n' +
        'down 5\n' +
        'down 1\n' +
        'forward 3\n' +
        'down 7\n' +
        'down 5\n' +
        'down 9\n' +
        'down 5\n' +
        'up 6\n' +
        'up 5\n' +
        'down 5\n' +
        'up 1\n' +
        'down 9\n' +
        'forward 5\n' +
        'forward 9\n' +
        'forward 3\n' +
        'forward 4\n' +
        'down 7\n' +
        'forward 3\n' +
        'forward 3\n' +
        'down 5\n' +
        'forward 7\n' +
        'down 9\n' +
        'forward 8\n' +
        'forward 4\n' +
        'forward 8\n' +
        'forward 9\n' +
        'forward 1\n' +
        'forward 6\n' +
        'up 9\n' +
        'down 3\n' +
        'forward 1\n' +
        'forward 4\n' +
        'down 2\n' +
        'down 8\n' +
        'up 4\n' +
        'down 4\n' +
        'forward 1\n' +
        'down 5\n' +
        'down 3\n' +
        'down 9\n' +
        'up 1\n' +
        'forward 8\n' +
        'down 6\n' +
        'down 4\n' +
        'forward 3\n' +
        'down 8\n' +
        'down 2\n' +
        'up 6\n' +
        'down 5\n' +
        'forward 8\n' +
        'down 4\n' +
        'up 1\n' +
        'forward 5\n' +
        'down 1\n' +
        'down 9\n' +
        'down 1\n' +
        'down 9\n' +
        'down 3\n' +
        'down 3\n' +
        'forward 2\n' +
        'forward 6\n' +
        'down 8\n' +
        'forward 1\n' +
        'up 4\n' +
        'down 3\n' +
        'forward 9\n' +
        'up 2\n' +
        'down 4\n' +
        'forward 9\n' +
        'down 3\n' +
        'down 1\n' +
        'down 3\n' +
        'down 4\n' +
        'up 6\n' +
        'down 2\n' +
        'forward 3\n' +
        'forward 9\n' +
        'forward 7\n' +
        'down 2\n' +
        'down 5\n' +
        'forward 4\n' +
        'forward 5\n' +
        'down 9\n' +
        'up 3\n' +
        'forward 5\n' +
        'forward 9\n' +
        'up 2\n' +
        'forward 3\n' +
        'down 4\n' +
        'forward 2\n' +
        'down 5\n' +
        'down 8\n' +
        'down 1\n' +
        'forward 4\n' +
        'up 4\n' +
        'forward 7\n' +
        'down 9\n' +
        'forward 8\n' +
        'down 8\n' +
        'forward 3\n' +
        'down 6\n' +
        'up 9\n' +
        'up 6\n' +
        'down 2\n' +
        'forward 6\n' +
        'up 1\n' +
        'down 5\n' +
        'down 5\n' +
        'down 9\n' +
        'up 2\n' +
        'down 2\n' +
        'forward 1\n' +
        'forward 8\n' +
        'down 2\n' +
        'up 8\n' +
        'down 3\n' +
        'forward 2\n' +
        'down 1\n' +
        'down 5\n' +
        'down 5\n' +
        'up 4\n' +
        'forward 5\n';

    const formattedData = data.split('\n').slice(0, -1).map(str => str.split(' '));
    const FORWARD = 'forward';
    const UP = 'up';
    const DOWN = 'down';

    let aim = 0;
    let horizontalPosition = 0;
    let depth = 0;

    formattedData.forEach(([command, val]) => {

        const value = +val;
        switch (command) {
            case FORWARD:
                horizontalPosition += value;
                depth += aim * value;
                break;
            case UP:
                aim = (aim - value) >= 0 ? aim - value : 0;
                break;
            case DOWN:
                aim += value;
                break;
        }
    });

    console.log('horizontalPosition_2', horizontalPosition);
    console.log('depth_2', depth);
    console.log('aim_2', aim);
    console.log('result_2', horizontalPosition * depth);
})();